close #8 【記事追加】2020年度p5.js講座
dot-cube/dot-cube.github.io pull request #11
Opened 2020-10-27 15:48 UTC by nssuperx

2020年プログラミング講座の記事を追加．
`data/portfolio.yml` を触ったので**コンフリクトします．**

2020-10-27 19:30 UTC, Takahiro55555 requested changes
#### `title.jpg` に関して
サムネの画像は、表示が崩れてしまうため `820 px`×` 520 px` くらいのサイズでお願いします。

![image](https://user-images.githubusercontent.com/31930148/97351579-4afb0e80-18d5-11eb-9384-dfb3c97dd3ef.png)

#### その他の画像について
画像の高さには暗黙の上限を設けています。
縦長の画像などの場合、こうしないと画面の大半を画像が占めてしまうためです...
あと、無用にファイルサイズを増やさないためでもあります。

そのため、`520 px`以下の高さにしてもらえると助かります。  

このことも、あとでREADMEに書かないといけないな...

#### その他
実際にローカルで表示してみましたが、良いと思います！！！  
LGTM

2020-10-28 01:28 UTC, nssuperx commented
ありがとう！小さくしました。

2020-10-28 11:15 UTC, Takahiro55555 requested changes

2020-10-28 11:15 UTC, Takahiro55555 commented on data/portfolio.yml
> +    category: "event"
末尾に追加すると、Portfolio 一覧表示の際に最下部に表示されてしまうようです。 
Portfolio 一覧の上のほうに新しいものを表示したいので、先頭に追加してもらえると助かります。

![dot-cube github io-preview-01](https://user-images.githubusercontent.com/31930148/97424497-24c88380-1954-11eb-9da4-c2761d3a091d.PNG)

2020-10-28 13:52 UTC, nssuperx commented
そこまで気が回りませんでした。修正しました。

2020-10-28 13:56 UTC, nssuperx commented on data/portfolio.yml
> +    category: "event"
そこまで気が回りませんでした。修正しました。

2020-10-29 03:19 UTC, Takahiro55555 approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/94754)

2020-10-29 03:19 UTC, merged