close #9 【記事追加】部員のTouch DesignerによるVJソフト
dot-cube/dot-cube.github.io pull request #13
Opened 2020-10-29 15:05 UTC by nssuperx

VJシステムの記事です。
文章が少ないかな...

2020-11-02 16:36 UTC, Takahiro55555 commented
プレビューページ  
[https://13.dot-cube.github.io.preview.moyashi.dev/](https://13.dot-cube.github.io.preview.moyashi.dev/)

はやくプルリクエストとの連携をしたい...

2020-11-02 16:53 UTC, Takahiro55555 requested changes
サムネ画像の修正をお願いします。
サムネとして表示する画像と作品紹介用に表示する画像を分けて、サムネのほうは規定サイズ（820 x 512）になるように切り抜くと良いと思います。

![dot-cube github io-preview-03](https://user-images.githubusercontent.com/31930148/97895383-0e1c9500-1d77-11eb-8f9d-a3043260e9a1.PNG)

2020-11-03 02:19 UTC, nssuperx commented
修正しました、2020プログラミング体験講座のも修正せなんな...
まとめてコミットしていいなら修正したいです。

2020-11-03 22:53 UTC, Takahiro55555 approved these changes
レビューが遅れてすいません...
プレビューを確認したところ、完璧だと思います！！！

![LGTM](https://cdn.lgtmoon.dev/images/90781)

2020-11-03 22:53 UTC, merged